language: php
php:
    - 5.5
    - 5.6
install:
    - composer install
before_script: phpenv config-add doc/myconfig.ini
script:
    - sudo find -L ./core -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    - phpunit --bootstrap app/test.php core/Group
