language: php
php:
    - 5.5
    - 5.6
    - 7.0
install:
    - composer install
script:
    - sudo find -L ./core -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    - wget https://phar.phpunit.de/phpunit.phar
    - chmod +x phpunit.phar
    - sudo mv phpunit.phar /usr/local/bin/phpunit
    - phpunit --version
    - phpunit --bootstrap app/test.php core/Group
